
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLConnection;
import org.json.JSONObject;


public class BookSearch extends java.awt.Frame {

    /**
     * Creates new form BookSearch
     */
    public BookSearch() {
        initComponents();
        setSize(500,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        t1 = new java.awt.TextField();
        button1 = new java.awt.Button();
        label6 = new java.awt.Label();
        t2 = new java.awt.TextField();
        label7 = new java.awt.Label();
        t3 = new java.awt.TextField();
        label8 = new java.awt.Label();
        t4 = new java.awt.TextField();
        label9 = new java.awt.Label();
        t5 = new java.awt.TextField();
        button2 = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setText("Code");
        add(label1);
        label1.setBounds(60, 90, 100, 30);
        add(t1);
        t1.setBounds(200, 90, 170, 30);

        button1.setLabel("Search");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(430, 90, 57, 24);

        label6.setText("Title");
        add(label6);
        label6.setBounds(60, 150, 27, 20);
        add(t2);
        t2.setBounds(200, 150, 170, 30);

        label7.setText("Subject");
        add(label7);
        label7.setBounds(60, 230, 60, 20);
        add(t3);
        t3.setBounds(200, 220, 170, 30);

        label8.setText("Author");
        add(label8);
        label8.setBounds(60, 290, 39, 20);
        add(t4);
        t4.setBounds(200, 280, 170, 30);

        label9.setText("Price");
        add(label9);
        label9.setBounds(60, 350, 32, 20);
        add(t5);
        t5.setBounds(200, 350, 170, 30);

        button2.setLabel("Update");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2);
        button2.setBounds(200, 420, 56, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        //we are going to call a rest-api 
        
        String code=t1.getText();   //we are reading text entered in textfield
        String endPoint="http://localhost:8080/rest-one/book/json/"+code;
        try {
            URL url=new URL(endPoint);
            URLConnection con=url.openConnection();
            InputStream is=con.getInputStream();
            String result="";
            while(true){
                int n=is.read();
                if(n==-1)break;
                result=result+(char)n;
            }
            is.close();
            System.out.println(result);
            //result variable holds a json string 
            //now we will parse the string and show it on our ui.
            JSONObject json=new JSONObject(result);
            String title=json.getString("title");
            String subject=json.getString("subject");
            String author=json.getString("author");
            int price=json.getInt("price");
            t2.setText(title);
            t3.setText(author);
            t4.setText(subject);
            t5.setText(""+price);
            
            
        } catch (Exception ex) {
           ex.printStackTrace();
        }
        
        
        
        
        
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        //reading user inputs
        String code=t1.getText();
        String title=t2.getText();
        String subject=t3.getText();
        String author=t4.getText();
        String price=t5.getText();
        //creating a json object to be send to api along with request
        JSONObject json=new JSONObject();
        json.put("code", Integer.parseInt(code));
        json.put("title",title);
        json.put("subject",subject);
        json.put("author",author);
        json.put("price", Integer.parseInt(price));
        String jsonStr=json.toString();
        System.out.println(jsonStr);
        //sending a post request 
        String endPoint="http://localhost:8080/rest-one/book";
        try{
            URL url=new URL(endPoint);
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setDoInput(true);
            con.setDoOutput(true);
            con.setRequestMethod("PUT");
            con.setRequestProperty("Content-Type", "application/json");
            con.setRequestProperty("Accept", "application/json");
            //we will send the data using OutputStream
            OutputStream os=con.getOutputStream();
            os.write(jsonStr.getBytes());
            os.flush();
            os.close();
            //we will receive the response using InputStream
            InputStream is=con.getInputStream();
            String res="";
            BufferedReader br=new BufferedReader(new InputStreamReader(is));
            while(true){
                String line=br.readLine();
                if(line==null)break;
                res=res+line;
            }
            System.out.println(res);
            is.close();
         
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookSearch().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Label label1;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextField t1;
    private java.awt.TextField t2;
    private java.awt.TextField t3;
    private java.awt.TextField t4;
    private java.awt.TextField t5;
    // End of variables declaration//GEN-END:variables
}
