
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import org.json.JSONObject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SSI
 */
public class BookEntry extends java.awt.Frame {

    /**
     * Creates new form BookEntry
     */
    public BookEntry() {
        initComponents();
        setSize(600,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        t1 = new java.awt.TextField();
        t2 = new java.awt.TextField();
        t3 = new java.awt.TextField();
        t4 = new java.awt.TextField();
        t5 = new java.awt.TextField();
        button1 = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setText("Code");
        add(label1);
        label1.setBounds(140, 90, 90, 20);

        label2.setText("Title");
        add(label2);
        label2.setBounds(140, 140, 27, 20);

        label3.setText("Subject");
        add(label3);
        label3.setBounds(140, 190, 50, 20);

        label4.setText("Author");
        add(label4);
        label4.setBounds(140, 240, 39, 20);

        label5.setText("Price");
        add(label5);
        label5.setBounds(140, 290, 32, 20);
        add(t1);
        t1.setBounds(300, 90, 190, 20);
        add(t2);
        t2.setBounds(300, 140, 190, 20);
        add(t3);
        t3.setBounds(300, 190, 190, 20);
        add(t4);
        t4.setBounds(300, 240, 190, 20);
        add(t5);
        t5.setBounds(300, 290, 190, 20);

        button1.setLabel("Save");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(270, 360, 120, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        //reading user inputs
        String code=t1.getText();
        String title=t2.getText();
        String subject=t3.getText();
        String author=t4.getText();
        String price=t5.getText();
        //creating a json object to be send to api along with request
        JSONObject json=new JSONObject();
        json.put("code", Integer.parseInt(code));
        json.put("title",title);
        json.put("subject",subject);
        json.put("author",author);
        json.put("price", Integer.parseInt(price));
        String jsonStr=json.toString();
        System.out.println(jsonStr);
        //sending a post request 
        String endPoint="http://localhost:8080/rest-one/book";
        try{
            URL url=new URL(endPoint);
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setDoInput(true);
            con.setDoOutput(true);
            con.setRequestMethod("POST");
            con.setRequestProperty("Content-Type", "application/json");
            con.setRequestProperty("Accept", "application/json");
            //we will send the data using OutputStream
            OutputStream os=con.getOutputStream();
            os.write(jsonStr.getBytes());
            os.flush();
            os.close();
            //we will receive the response using InputStream
            InputStream is=con.getInputStream();
            String res="";
            BufferedReader br=new BufferedReader(new InputStreamReader(is));
            while(true){
                String line=br.readLine();
                if(line==null)break;
                res=res+line;
            }
            System.out.println(res);
            is.close();
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");

        }catch(Exception e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookEntry().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.TextField t1;
    private java.awt.TextField t2;
    private java.awt.TextField t3;
    private java.awt.TextField t4;
    private java.awt.TextField t5;
    // End of variables declaration//GEN-END:variables
}
